import type { Collection, Link } from '../types';

/** Mock user matching Profile screen in HTML source of truth. */
export const mockUser = {
  id: '00000000-0000-0000-0000-000000000001',
  name: 'Alex',
  email: 'alex@example.com',
};

export const mockCollections: Collection[] = [
  {
    id: 'c-read-later',
    user_id: mockUser.id,
    name: 'Read Later',
    icon_key: 'heart',
    color_key: 'pink',
    link_count: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-work',
    user_id: mockUser.id,
    name: 'Work',
    icon_key: 'briefcase',
    color_key: 'blue',
    link_count: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-personal',
    user_id: mockUser.id,
    name: 'Personal',
    icon_key: 'user',
    color_key: 'teal',
    link_count: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-inspiration',
    user_id: mockUser.id,
    name: 'Inspiration',
    icon_key: 'sparkles',
    color_key: 'orange',
    link_count: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-tools',
    user_id: mockUser.id,
    name: 'Tools',
    icon_key: 'box',
    color_key: 'blue',
    link_count: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

/** Mock links matching Home + Collection View screens. */
export const mockLinks: Link[] = [
  {
    id: 'l-1',
    user_id: mockUser.id,
    canonical_url: 'https://nngroup.com/design-forms',
    original_url: 'https://nngroup.com/design-forms',
    title: 'Design Better Forms',
    description: 'Form design guidelines.',
    source_domain: 'nngroup.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
  },
  {
    id: 'l-2',
    user_id: mockUser.id,
    canonical_url: 'https://fs.blog/focus',
    original_url: 'https://fs.blog/focus',
    title: 'A Guide to Focus',
    description: 'How to focus deeply.',
    source_domain: 'fs.blog',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '5h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-work'],
  },
  {
    id: 'l-3',
    user_id: mockUser.id,
    canonical_url: 'https://awwwards.com',
    original_url: 'https://awwwards.com',
    title: 'Beautiful Web Apps',
    description: 'Award-winning web design.',
    source_domain: 'awwwards.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '1d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-inspiration'],
  },
  {
    id: 'l-4',
    user_id: mockUser.id,
    canonical_url: 'https://notion.so',
    original_url: 'https://notion.so',
    title: 'Notion for Creators',
    description: 'Create and organize.',
    source_domain: 'notion.so',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-tools'],
  },
  {
    id: 'l-sleep',
    user_id: mockUser.id,
    canonical_url: 'https://hubermanlab.com/sleep',
    original_url: 'https://hubermanlab.com/sleep',
    title: 'The Science of Better Sleep',
    description:
      'Learn how sleep affects your brain, performance, and overall health — and practical tips to improve it.',
    source_domain: 'hubermanlab.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
  },
];
