import type { Collection, Link } from '../types';

/** Mock user matching Profile screen in HTML source of truth. */
export const mockUser = {
  id: '00000000-0000-0000-0000-000000000001',
  name: 'Alex',
  email: 'alex@example.com',
};

export const mockCollections: Collection[] = [
  {
    id: 'c-read-later',
    user_id: mockUser.id,
    name: 'Read Later',
    icon_key: 'heart',
    color_key: 'pink',
    link_count: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-work',
    user_id: mockUser.id,
    name: 'Work',
    icon_key: 'briefcase',
    color_key: 'blue',
    link_count: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-personal',
    user_id: mockUser.id,
    name: 'Personal',
    icon_key: 'user',
    color_key: 'teal',
    link_count: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-inspiration',
    user_id: mockUser.id,
    name: 'Inspiration',
    icon_key: 'sparkles',
    color_key: 'orange',
    link_count: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-tools',
    user_id: mockUser.id,
    name: 'Tools',
    icon_key: 'box',
    color_key: 'blue',
    link_count: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

/** Mock links matching Home + Collection View screens. */
export const mockLinks: Link[] = [
  {
    id: 'l-1',
    user_id: mockUser.id,
    canonical_url: 'https://nngroup.com/design-forms',
    original_url: 'https://nngroup.com/design-forms',
    title: 'Design Better Forms',
    description: 'Form design guidelines.',
    source_domain: 'nngroup.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { bg: '#fde3ea', icon: 'heart', iconColor: '#f2436a' },
  },
  {
    id: 'l-2',
    user_id: mockUser.id,
    canonical_url: 'https://fs.blog/focus',
    original_url: 'https://fs.blog/focus',
    title: 'A Guide to Focus',
    description: 'How to focus deeply.',
    source_domain: 'fs.blog',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '5h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-work'],
    thumb: { bg: '#1c1d21', label: 'F', labelColor: '#fff' },
  },
  {
    id: 'l-3',
    user_id: mockUser.id,
    canonical_url: 'https://awwwards.com',
    original_url: 'https://awwwards.com',
    title: 'Beautiful Web Apps',
    description: 'Award-winning web design.',
    source_domain: 'awwwards.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '1d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-inspiration'],
    thumb: { gradient: ['#3a3f47', '#15171a'], label: 'A', labelColor: '#fff' },
  },
  {
    id: 'l-4',
    user_id: mockUser.id,
    canonical_url: 'https://notion.so',
    original_url: 'https://notion.so',
    title: 'Notion for Creators',
    description: 'Create and organize.',
    source_domain: 'notion.so',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-tools'],
    thumb: { bg: '#000', label: 'N', labelColor: '#fff' },
  },
  {
    id: 'l-sleep',
    user_id: mockUser.id,
    canonical_url: 'https://hubermanlab.com/sleep',
    original_url: 'https://hubermanlab.com/sleep',
    title: 'The Science of Better Sleep',
    description:
      'Learn how sleep affects your brain, performance, and overall health — and practical tips to improve it.',
    source_domain: 'hubermanlab.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { gradient: ['#3a6288', '#0d1c2c'] },
  },
];

/** Collection View rows — exact content from the HTML source. */
export const mockCollectionLinks: Link[] = [
  {
    id: 'cv-1',
    user_id: mockUser.id,
    canonical_url: 'https://hubermanlab.com/sleep',
    original_url: 'https://hubermanlab.com/sleep',
    title: 'The Science of Better Sleep',
    description: 'Sleep and performance.',
    source_domain: 'hubermanlab.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '2h ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { gradient: ['#3a6288', '#0d1c2c'] },
  },
  {
    id: 'cv-2',
    user_id: mockUser.id,
    canonical_url: 'https://nytimes.com/health',
    original_url: 'https://nytimes.com/health',
    title: 'A Healthier, Happier You',
    description: 'Health and happiness.',
    source_domain: 'nytimes.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '1d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { bg: '#111', label: 'T', labelColor: '#fff', serif: true },
  },
  {
    id: 'cv-3',
    user_id: mockUser.id,
    canonical_url: 'https://theminimalists.com',
    original_url: 'https://theminimalists.com',
    title: 'Minimalist Living',
    description: 'Live with less.',
    source_domain: 'theminimalists.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '3d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { bg: '#dcdfe4' },
  },
  {
    id: 'cv-4',
    user_id: mockUser.id,
    canonical_url: 'https://medium.com/wellbeing',
    original_url: 'https://medium.com/wellbeing',
    title: 'Digital Wellbeing',
    description: 'Balance with technology.',
    source_domain: 'medium.com',
    preview_image_url: null,
    metadata_status: 'ready',
    saved_at: '5d ago',
    updated_at: new Date().toISOString(),
    collection_ids: ['c-read-later'],
    thumb: { bg: '#000', label: 'M', labelColor: '#fff' },
  },
];
